version: '3.9'

services:
  nextjs:
    build: .
    image: kazimovzaman2/agileflow-dash:latest
    container_name: agileflow-dash
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
